version: '3'
services:
  db:
    image: postgres:15.3-bullseye
    deploy:
      resources:
        reservations:
          memory: 128M
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
  adminer:
    image: adminer
    deploy:
      resources:
        reservations:
          memory: 128M
    ports:
      - 8090:8080
  backend:
    platform: linux/amd64
    deploy:
      resources:
        reservations:
          memory: 1024M
    build: .
    depends_on:
      - db
    working_dir: /app
    volumes:
      - /app
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${SPRING_DATASOURCE_DATABASE}
      SECRET: ${SECRET}
      S3_FILE_UPLOAD_BUCKET: ${S3_FILE_UPLOAD_BUCKET}
      S3_FILE_UPLOAD_REGION: ${S3_FILE_UPLOAD_REGION}
      S3_FILE_UPLOAD_ACCESS_KEY_ID: ${S3_FILE_UPLOAD_ACCESS_KEY_ID}
      S3_FILE_UPLOAD_SECRET_ACCESS_KEY: ${S3_FILE_UPLOAD_SECRET_ACCESS_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI}
    ports:
      - 10800:10800

volumes:
  postgres-data:
