lamina:
  base-url: https://qa.app.laminafs.com
  environment: qa
  email-notification:
    process-interval: "0 */15 * * * *"
  email-service:
    enabled: true
    filter: true
  lambda:
    enabled: true
    dp-function-name: arn:aws:lambda:us-east-1:710894263335:function:lamina-fileManagerService
    dd-function-name: clientFileDownloadService-qa
  cognito:
    user-pool-id: us-east-1_ZNnEY17wP

spring:
  flyway:
    locations: classpath:/db/migration,classpath:/test/db/migration,classpath:/dev/db/migration
