package com.westmonroe.loansyndication.querydef.event;

public class EventParticipantFacilityQueryDef {

    private EventParticipantFacilityQueryDef() {
        throw new IllegalStateException("Utility class");
    }

    public static final String SELECT_EVENT_PARTICIPANT_FACILITY = """
        SELECT EPF.EVENT_PARTICIPANT_ID
             , EP.EVENT_ID
             , EI.EVENT_UUID
             , EI.EVENT_EXTERNAL_UUID
             , EI.EVENT_NAME
             , EP.PARTICIPANT_ID
             , II.INSTITUTION_UUID
             , II.INSTITUTION_NAME
             , EPF.EVENT_DEAL_FACILITY_ID
             , EDF.DEAL_FACILITY_ID
             , DF.FACILITY_EXTERNAL_UUID
             , DF.DEAL_ID
             , DF.FACILITY_NAME
             , DF.FACILITY_AMT
             , DF.FACILITY_TYPE_ID
             , COALESCE(PD.OPTION_NAME, '') AS FACILITY_TYPE_NAME
             , EPF.INVITATION_AMT
             , EPF.COMMITMENT_AMT
             , EPF.ALLOCATION_AMT
             , EPF.CREATED_BY_ID
             , UIC.USER_UUID AS CREATED_BY_UUID
             , UIC.FIRST_NAME AS CREATED_BY_FIRST_NAME
             , UIC.LAST_NAME AS CREATED_BY_LAST_NAME
             , UIC.EMAIL_ADDR AS CREATED_BY_EMAIL_ADDR
             , UIC.PASSWORD_DESC AS CREATED_BY_PASSWORD_DESC
             , UIC.ACTIVE_IND AS CREATED_BY_ACTIVE_IND
             , EPF.CREATED_DATE
             , EPF.UPDATED_BY_ID
             , UIU.USER_UUID AS UPDATED_BY_UUID
             , UIU.FIRST_NAME AS UPDATED_BY_FIRST_NAME
             , UIU.LAST_NAME AS UPDATED_BY_LAST_NAME
             , UIU.EMAIL_ADDR AS UPDATED_BY_EMAIL_ADDR
             , UIU.PASSWORD_DESC AS UPDATED_BY_PASSWORD_DESC
             , UIU.ACTIVE_IND AS UPDATED_BY_ACTIVE_IND
             , EPF.UPDATED_DATE
          FROM EVENT_PARTICIPANT_FACILITY EPF LEFT JOIN EVENT_PARTICIPANT EP
            ON EPF.EVENT_PARTICIPANT_ID = EP.EVENT_PARTICIPANT_ID LEFT JOIN EVENT_INFO EI
            ON EP.EVENT_ID = EI.EVENT_ID LEFT JOIN INSTITUTION_INFO II
            ON EP.PARTICIPANT_ID = II.INSTITUTION_ID LEFT JOIN EVENT_DEAL_FACILITY EDF
            ON EPF.EVENT_DEAL_FACILITY_ID = EDF.EVENT_DEAL_FACILITY_ID LEFT JOIN DEAL_FACILITY DF
            ON EDF.DEAL_FACILITY_ID = DF.DEAL_FACILITY_ID LEFT JOIN PICKLIST_DEF PD
            ON DF.FACILITY_TYPE_ID = PD.PICKLIST_ID LEFT JOIN USER_INFO UIC
            ON EPF.CREATED_BY_ID = UIC.USER_ID LEFT JOIN USER_INFO UIU
            ON EPF.UPDATED_BY_ID = UIU.USER_ID
    """;

    public static final String INSERT_EVENT_PARTICIPANT_FACILITY = """
        INSERT INTO EVENT_PARTICIPANT_FACILITY
             ( EVENT_PARTICIPANT_ID, EVENT_DEAL_FACILITY_ID, INVITATION_AMT, COMMITMENT_AMT, ALLOCATION_AMT, CREATED_BY_ID, UPDATED_BY_ID )
               VALUES
             ( ?, ?, ?, ?, ?, ?, ? )
    """;
    public static final String UPDATE_EVENT_PARTICIPANT_FACILITY = """
        UPDATE EVENT_PARTICIPANT_FACILITY
           SET INVITATION_AMT = ?
             , COMMITMENT_AMT = ?
             , ALLOCATION_AMT = ?
             , UPDATED_BY_ID = ?
             , UPDATED_DATE = CURRENT_TIMESTAMP
         WHERE EVENT_PARTICIPANT_ID = ?
           AND EVENT_DEAL_FACILITY_ID = ?
    """;
    public static final String REMOVE_EVENT_PARTICIPANT_FACILITY_ALLOCATIONS = """
        UPDATE EVENT_PARTICIPANT_FACILITY
           SET ALLOCATION_AMT = NULL
         WHERE EVENT_PARTICIPANT_ID = ?
    """;
    public static final String DELETE_EVENT_PARTICIPANT_FACILITY = "DELETE FROM EVENT_PARTICIPANT_FACILITY";

}