-- Drop the lead date columns from the Event Lead Facility table.
ALTER TABLE EVENT_LEAD_FACILITY
 DROP COLUMN INVITATION_DATE,
 DROP COLUMN COMMITMENT_DATE,
 DROP COLUMN ALLOCATION_DATE;

-- Add the lead date columns to the Event table.
ALTER TABLE EVENT_INFO
  ADD COLUMN LEAD_INVITATION_DATE TIMESTAMP WITH TIME ZONE NULL,
  ADD COLUMN LEAD_COMMITMENT_DATE TIMESTAMP WITH TIME ZONE NULL,
  ADD COLUMN LEAD_ALLOCATION_DATE TIMESTAMP WITH TIME ZONE NULL;