------------------------------------
--    Create Definition Tables    --
------------------------------------
CREATE TABLE ROLE_DEF (
    ROLE_ID                     SERIAL      NOT NULL,
    ROLE_CD                     VARCHAR(25) NOT NULL,
    ROLE_NAME                   VARCHAR(35) NOT NULL,
    ROLE_DESC                   VARCHAR(255),
    VISIBLE_IND                 VARCHAR(1)  NOT NULL DEFAULT 'Y',
    PRIMARY KEY ( ROLE_ID ),
    UNIQUE ( ROLE_CD )
);

CREATE TABLE STAGE_DEF (
    STAGE_ID                    SERIAL       NOT NULL,
    STAGE_NAME                  VARCHAR(50)  NOT NULL,
    TITLE_DESC                  VARCHAR(50)  NULL,
    SUBTITLE_DESC               VARCHAR(255) NULL,
    ORDER_NBR                   INTEGER      NOT NULL,
    PRIMARY KEY ( STAGE_ID ),
    UNIQUE ( ORDER_NBR )
);

CREATE TABLE PARTICIPANT_STEP_DEF (
    PARTICIPANT_STEP_ID         SERIAL       NOT NULL,
    STEP_NAME                   VARCHAR(100) NOT NULL,
    ORIG_STATUS_DESC            VARCHAR(100) NULL,
    PART_STATUS_DESC            VARCHAR(300) NULL,
    ORDER_NBR                   INTEGER      NOT NULL,
    PRIMARY KEY ( PARTICIPANT_STEP_ID ),
    UNIQUE ( ORDER_NBR )
);

CREATE TABLE DOCUMENT_CATEGORY_DEF (
    DOCUMENT_CATEGORY_ID        SERIAL      NOT NULL,
    DOCUMENT_CATEGORY_NAME      VARCHAR(40) NOT NULL,
    ORDER_NBR                   INTEGER     NOT NULL,
    DEAL_DOCUMENT_IND           VARCHAR(1)  NOT NULL DEFAULT 'N',
    PRIMARY KEY ( DOCUMENT_CATEGORY_ID ),
    UNIQUE ( ORDER_NBR )
);

CREATE TABLE PICKLIST_CATEGORY_DEF (
    PICKLIST_CATEGORY_ID        SERIAL NOT NULL,
    PICKLIST_CATEGORY_NAME      VARCHAR(100) NOT NULL,
    PRIMARY KEY ( PICKLIST_CATEGORY_ID ),
    UNIQUE ( PICKLIST_CATEGORY_NAME )
);

CREATE TABLE PICKLIST_DEF (
    PICKLIST_ID                 SERIAL       NOT NULL,
    PICKLIST_CATEGORY_ID        INTEGER      NOT NULL,
    OPTION_NAME                 VARCHAR(100) NOT NULL,
    ORDER_NBR                   INTEGER      NOT NULL,
    PRIMARY KEY ( PICKLIST_ID ),
    UNIQUE ( PICKLIST_CATEGORY_ID, OPTION_NAME ),
    UNIQUE ( PICKLIST_CATEGORY_ID, ORDER_NBR ),
    FOREIGN KEY ( PICKLIST_CATEGORY_ID ) REFERENCES PICKLIST_CATEGORY_DEF ( PICKLIST_CATEGORY_ID )
);

CREATE TABLE STATE_DEF (
    STATE_CD                    VARCHAR(2)   NOT NULL,
    STATE_NAME                  VARCHAR(50)  NOT NULL,
    PRIMARY KEY ( STATE_CD )
);

CREATE TABLE EVENT_TYPE_DEF (
    EVENT_TYPE_ID               SERIAL       NOT NULL,
    EVENT_TYPE_NAME             VARCHAR(35)  NOT NULL,
    PRIMARY KEY ( EVENT_TYPE_ID )
);

------------------------------------
--    Create NAICS Code Table     --
------------------------------------
CREATE TABLE NAICS_DEF (
    NAICS_CD          VARCHAR(6) NOT NULL,
    TITLE_NAME        VARCHAR(150) NOT NULL,
    PRIMARY KEY ( NAICS_CD )
);

------------------------------------
--   Create Initial Lender Table  --
------------------------------------
CREATE TABLE INITIAL_LENDER_INFO (
    INITIAL_LENDER_ID           SERIAL NOT NULL,
    LENDER_NAME                 VARCHAR(80) NOT NULL,
    CREATED_DATE                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ACTIVE_IND                  VARCHAR(1) DEFAULT 'N' NOT NULL,
    PRIMARY KEY ( INITIAL_LENDER_ID ),
    UNIQUE ( LENDER_NAME )
);

------------------------------------
--    Create Institution Table    --
------------------------------------
CREATE TABLE INSTITUTION_INFO (
    INSTITUTION_ID              SERIAL NOT NULL,
    INSTITUTION_UUID            VARCHAR(36) NOT NULL,
    INSTITUTION_NAME            VARCHAR(80) NOT NULL,
    BRAND_NAME                  VARCHAR(255),
    COMMUNITY_EXT_DESC          VARCHAR(250),
    COMMUNITY_NAME              VARCHAR(255),
    COMMUNITY_NETWORK_ID        VARCHAR(25),
    LOOKUP_KEY_DESC             VARCHAR(255),
    OWNER_NAME                  VARCHAR(255),
    PERMISSION_SET_DESC         VARCHAR(250),
    SSO_IND                     VARCHAR(1) DEFAULT 'N' NOT NULL,
    ACTIVE_IND                  VARCHAR(1) DEFAULT 'N' NOT NULL,
    PRIMARY KEY ( INSTITUTION_ID ),
    UNIQUE ( INSTITUTION_UUID ),
    UNIQUE ( INSTITUTION_NAME )
);

------------------------------------
--       Create User Table        --
------------------------------------
CREATE TABLE USER_INFO (
    USER_ID                     SERIAL NOT NULL,
    USER_UUID                   VARCHAR(36) NOT NULL,
    INSTITUTION_ID              INTEGER NULL,
    FIRST_NAME                  VARCHAR(40) NOT NULL,
    LAST_NAME                   VARCHAR(80) NOT NULL,
    EMAIL_ADDR                  VARCHAR(255),
    PASSWORD_DESC               VARCHAR(255),
    ACTIVE_IND                  VARCHAR(1) DEFAULT 'N' NOT NULL,
    CREATED_DATE                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ( USER_ID ),
    CONSTRAINT UC_USER_INFO_USER_UUID UNIQUE ( USER_UUID ),
    CONSTRAINT UC_USER_INFO_EMAIL_ADDR UNIQUE ( EMAIL_ADDR ),
    FOREIGN KEY ( INSTITUTION_ID ) REFERENCES INSTITUTION_INFO ( INSTITUTION_ID )
);

--------------------------------------------
-- Create User Role Cross Reference Table --
--------------------------------------------
CREATE TABLE USER_ROLE_XREF (
    USER_ID                    INTEGER NOT NULL,
    ROLE_ID                    INTEGER NOT NULL,
    PRIMARY KEY ( USER_ID, ROLE_ID ),
    FOREIGN KEY ( USER_ID ) REFERENCES USER_INFO ( USER_ID ),
    FOREIGN KEY ( ROLE_ID ) REFERENCES ROLE_DEF ( ROLE_ID )
);

------------------------------------
--       Create Deal Table        --
------------------------------------
CREATE TABLE DEAL_INFO (
    DEAL_ID                     SERIAL NOT NULL,
    DEAL_UUID                   VARCHAR(36) NOT NULL,
    DEAL_EXTERNAL_UUID          VARCHAR(55) NOT NULL,
    DEAL_NAME                   VARCHAR(80) NOT NULL,
    DEAL_INDUSTRY_ID            INTEGER NOT NULL DEFAULT 15,
    ORIGINATOR_ID               INTEGER NOT NULL,
    INITIAL_LENDER_IND          VARCHAR(1) NOT NULL DEFAULT 'N',
    INITIAL_LENDER_ID           INTEGER NULL,
    STAGE_ID                    INTEGER NOT NULL,
    DEAL_STRUCTURE_ID           INTEGER NOT NULL,
    DEAL_TYPE_DESC              VARCHAR(50),
    DEAL_DESC                   TEXT NULL,
    DEAL_AMT                    DECIMAL(12, 2) DEFAULT 0,
    LAST_FACILITY_NBR           INTEGER NOT NULL DEFAULT 0,
    APPLICANT_EXTERNAL_UUID     VARCHAR(55) NOT NULL,
    BORROWER_DESC               TEXT,
    BORROWER_NAME               VARCHAR(255) NOT NULL,
    BORROWER_CITY_NAME          VARCHAR(50) NULL,
    BORROWER_STATE_CD           VARCHAR(2) NULL,
    BORROWER_COUNTY_NAME        VARCHAR(50) NULL,
    FARM_CR_ELIG_ID             INTEGER NULL,
    TAX_ID_NBR                  VARCHAR(15) NOT NULL,
    BORROWER_INDUSTRY_CD        VARCHAR(6),
    BUSINESS_AGE_QTY            INTEGER NULL,
    DEFAULT_PROB_PCT            INTEGER NULL,
    DEBT_SRV_COV_RATIO          DECIMAL(12, 5) NULL,
    CY_EBITA_AMT                DECIMAL(12, 2) NULL,
    PATR_ELIG_IND               VARCHAR(1) NULL,
    CANCELED_DATE               TIMESTAMP WITH TIME ZONE NULL,
    COMPLETED_DATE              TIMESTAMP WITH TIME ZONE NULL,
    CREATED_BY_ID               INTEGER NOT NULL,
    CREATED_DATE                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY_ID               INTEGER NOT NULL,
    UPDATED_DATE                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ACTIVE_IND                  VARCHAR(1) DEFAULT 'N' NOT NULL,
    PRIMARY KEY ( DEAL_ID ),
    CONSTRAINT UC_DEAL_UUID UNIQUE ( DEAL_UUID ),
    CONSTRAINT UC_DEAL_EXTERNAL_UUID UNIQUE ( DEAL_EXTERNAL_UUID ),
    CONSTRAINT UC_DEAL_INFO_DEAL_NAME UNIQUE ( ORIGINATOR_ID, DEAL_NAME ),
    FOREIGN KEY ( ORIGINATOR_ID ) REFERENCES INSTITUTION_INFO ( INSTITUTION_ID ),
    FOREIGN KEY ( INITIAL_LENDER_ID ) REFERENCES INITIAL_LENDER_INFO ( INITIAL_LENDER_ID ),
    FOREIGN KEY ( STAGE_ID ) REFERENCES STAGE_DEF ( STAGE_ID ),
    FOREIGN KEY ( BORROWER_INDUSTRY_CD ) REFERENCES NAICS_DEF ( NAICS_CD ),
    FOREIGN KEY ( CREATED_BY_ID ) REFERENCES USER_INFO ( USER_ID ),
    FOREIGN KEY ( UPDATED_BY_ID ) REFERENCES USER_INFO ( USER_ID )
);

------------------------------------
--       Create Event Table       --
------------------------------------
CREATE TABLE EVENT_INFO (
    EVENT_ID                    SERIAL      NOT NULL,
    EVENT_UUID                  VARCHAR(36) NOT NULL,
    EVENT_EXTERNAL_UUID         VARCHAR(55) NOT NULL,
    DEAL_ID                     INTEGER     NOT NULL,
    EVENT_NAME                  VARCHAR(80) NOT NULL,
    EVENT_TYPE_ID               INTEGER NOT NULL,
    STAGE_ID                    INTEGER NOT NULL,
    PROJ_LAUNCH_DATE            DATE NULL,
    LAUNCH_DATE                 TIMESTAMP WITH TIME ZONE NULL,
    COMMITMENT_DATE             DATE NULL,
    COMMENTS_DUE_DATE           DATE NULL,
    EFFECTIVE_DATE              DATE NULL,
    CANCELED_DATE               TIMESTAMP WITH TIME ZONE NULL,
    PROJ_CLOSE_DATE             DATE NULL,
    CLOSE_DATE                  TIMESTAMP WITH TIME ZONE NULL,
    CREATED_BY_ID               INTEGER NOT NULL,
    CREATED_DATE                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY_ID               INTEGER NOT NULL,
    UPDATED_DATE                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ( EVENT_ID ),
    CONSTRAINT UC_EVENT_UUID UNIQUE ( EVENT_UUID ),
    CONSTRAINT UC_EVENT_EXTERNAL_UUID UNIQUE ( EVENT_EXTERNAL_UUID ),
    CONSTRAINT UC_EVENT_INFO_EVENT_NAME UNIQUE ( DEAL_ID, EVENT_NAME ),
    FOREIGN KEY ( DEAL_ID ) REFERENCES DEAL_INFO ( DEAL_ID ),
    FOREIGN KEY ( EVENT_TYPE_ID ) REFERENCES EVENT_TYPE_DEF ( EVENT_TYPE_ID ),
    FOREIGN KEY ( STAGE_ID ) REFERENCES STAGE_DEF ( STAGE_ID ),
    FOREIGN KEY ( CREATED_BY_ID ) REFERENCES USER_INFO ( USER_ID ),
    FOREIGN KEY ( UPDATED_BY_ID ) REFERENCES USER_INFO ( USER_ID )
);

------------------------------------
--  Create Deal Documents Table   --
------------------------------------
CREATE TABLE DEAL_DOCUMENT (
    DEAL_DOCUMENT_ID            SERIAL       NOT NULL,
    DEAL_ID                     INTEGER      NOT NULL,
    DISPLAY_NAME                VARCHAR(100) NOT NULL,
    DOCUMENT_NAME               VARCHAR(100) NOT NULL,
    DOCUMENT_CATEGORY_ID        INTEGER      NOT NULL,
    DOCUMENT_TYPE               VARCHAR(100) NOT NULL,
    DOCUMENT_DESC               VARCHAR(255) NULL,
    SOURCE_CD                   VARCHAR(1)   NOT NULL DEFAULT 'I',
    DOCUMENT_EXTERNAL_UUID      VARCHAR(55)  NOT NULL,
    CREATED_BY_ID               INTEGER NOT NULL,
    CREATED_DATE                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY_ID               INTEGER NOT NULL,
    UPDATED_DATE                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ( DEAL_DOCUMENT_ID ),
    FOREIGN KEY ( DEAL_ID ) REFERENCES DEAL_INFO ( DEAL_ID ),
    FOREIGN KEY ( DOCUMENT_CATEGORY_ID ) REFERENCES DOCUMENT_CATEGORY_DEF ( DOCUMENT_CATEGORY_ID ),
    FOREIGN KEY ( CREATED_BY_ID ) REFERENCES USER_INFO ( USER_ID ),
    FOREIGN KEY ( UPDATED_BY_ID ) REFERENCES USER_INFO ( USER_ID ),
    UNIQUE ( DEAL_ID, DOCUMENT_NAME ),
    UNIQUE ( DEAL_ID, DISPLAY_NAME ),
    UNIQUE ( DOCUMENT_EXTERNAL_UUID )
);

CREATE TABLE DEAL_MEMBER (
    DEAL_ID                     INTEGER NOT NULL,
    USER_ID                     INTEGER NOT NULL,
    MEMBER_TYPE_CD              VARCHAR(1) NOT NULL,
    CREATED_BY_ID               INTEGER NOT NULL,
    CREATED_DATE                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ( DEAL_ID, USER_ID ),
    FOREIGN KEY ( DEAL_ID ) REFERENCES DEAL_INFO ( DEAL_ID ),
    FOREIGN KEY ( USER_ID ) REFERENCES USER_INFO ( USER_ID ),
    FOREIGN KEY ( CREATED_BY_ID ) REFERENCES USER_INFO ( USER_ID )
);

------------------------------------
--   Create Deal Covenant Table   --
------------------------------------
CREATE TABLE DEAL_COVENANT (
    DEAL_COVENANT_ID            SERIAL       NOT NULL,
    COVENANT_EXTERNAL_UUID      VARCHAR(55)  NOT NULL,
    DEAL_ID                     INTEGER      NOT NULL,
    ENTITY_NAME                 VARCHAR(100) NULL,
    CATEGORY_NAME               VARCHAR(100) NOT NULL,
    COVENANT_TYPE_DESC          VARCHAR(100) NULL,
    FREQUENCY_DESC              VARCHAR(20)  NULL,
    NEXT_EVAL_DATE              DATE,
    EFFECTIVE_DATE              DATE,
    CREATED_BY_ID               INTEGER NOT NULL,
    CREATED_DATE                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY_ID               INTEGER NOT NULL,
    UPDATED_DATE                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ( DEAL_COVENANT_ID ),
    FOREIGN KEY ( DEAL_ID ) REFERENCES DEAL_INFO ( DEAL_ID ),
    FOREIGN KEY ( CREATED_BY_ID ) REFERENCES USER_INFO ( USER_ID ),
    FOREIGN KEY ( UPDATED_BY_ID ) REFERENCES USER_INFO ( USER_ID ),
    UNIQUE ( DEAL_ID, ENTITY_NAME, COVENANT_TYPE_DESC )
);

------------------------------------
--   Create Deal Facility Table   --
------------------------------------
CREATE TABLE DEAL_FACILITY (
    DEAL_FACILITY_ID            SERIAL       NOT NULL,
    FACILITY_EXTERNAL_UUID      VARCHAR(55)  NOT NULL,
    DEAL_ID                     INTEGER      NOT NULL,
    FACILITY_NAME               VARCHAR(100) NOT NULL,
    FACILITY_AMT                DECIMAL(12, 2) NOT NULL DEFAULT 0,
    FACILITY_TYPE_ID            INTEGER      NULL,
    TENOR_YRS_QTY               INTEGER      NULL,
    COLLATERAL_ID               INTEGER      NULL,
    PRICING_GRID_ID             INTEGER      NULL,
    PRICING_DESC                TEXT NULL,
    CSA_DESC                    TEXT NULL,
    FACILITY_PURPOSE_ID         INTEGER      NULL,
    PURPOSE_TEXT                TEXT         NULL,
    DAY_COUNT_ID                INTEGER      NULL,
    GUAR_INV_IND                VARCHAR(1)   NULL,
    FARM_CREDIT_TYPE_NAME       VARCHAR(5)   NULL,
    REV_UTIL_PCT                INTEGER NULL,
    UPFRONT_FEES_DESC           TEXT NULL,
    UNUSED_FEES_DESC            TEXT NULL,
    AMORTIZATION_DESC           TEXT NULL,
    MATURITY_DATE               DATE NULL,
    RENEWAL_DATE                DATE NULL,
    LGD_OPTION                  VARCHAR(1) NULL,
    PATRONAGE_PAYING_IND        VARCHAR(1) NULL DEFAULT 'N',
    CREATED_BY_ID               INTEGER NOT NULL,
    CREATED_DATE                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY_ID               INTEGER NOT NULL,
    UPDATED_DATE                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ( DEAL_FACILITY_ID ),
    FOREIGN KEY ( DEAL_ID ) REFERENCES DEAL_INFO ( DEAL_ID ),
    FOREIGN KEY ( PRICING_GRID_ID ) REFERENCES DEAL_DOCUMENT ( DEAL_DOCUMENT_ID ),
    FOREIGN KEY ( CREATED_BY_ID ) REFERENCES USER_INFO ( USER_ID ),
    FOREIGN KEY ( UPDATED_BY_ID ) REFERENCES USER_INFO ( USER_ID ),
    CONSTRAINT UC_FACILITY_EXTERNAL_UUID UNIQUE ( FACILITY_EXTERNAL_UUID )
);

------------------------------------
-- Create Event Participant Table --
------------------------------------
CREATE TABLE EVENT_PARTICIPANT (
    EVENT_PARTICIPANT_ID        SERIAL  NOT NULL,
    EVENT_ID                    INTEGER NOT NULL,
    PARTICIPANT_ID              INTEGER NULL,
    PARTICIPANT_STEP_ID         INTEGER NOT NULL,
    CREATED_BY_ID               INTEGER NOT NULL,
    CREATED_DATE                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY_ID               INTEGER NOT NULL,
    UPDATED_DATE                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ( EVENT_PARTICIPANT_ID ),
    UNIQUE ( EVENT_ID, PARTICIPANT_ID ),
    FOREIGN KEY ( EVENT_ID ) REFERENCES EVENT_INFO ( EVENT_ID ),
    FOREIGN KEY ( PARTICIPANT_ID ) REFERENCES INSTITUTION_INFO ( INSTITUTION_ID ),
    FOREIGN KEY ( PARTICIPANT_STEP_ID ) REFERENCES PARTICIPANT_STEP_DEF ( PARTICIPANT_STEP_ID ),
    FOREIGN KEY ( CREATED_BY_ID ) REFERENCES USER_INFO ( USER_ID ),
    FOREIGN KEY ( UPDATED_BY_ID ) REFERENCES USER_INFO ( USER_ID )
);

------------------------------------------------
-- Create Event Participant Origination Table --
------------------------------------------------
CREATE TABLE EVENT_PARTICIPANT_ORIGINATION (
    EVENT_PARTICIPANT_ID        INTEGER NOT NULL,
    INVITE_RECIPIENT_ID         INTEGER NULL,
    INVITE_DATE                 TIMESTAMP WITH TIME ZONE NULL,
    FULL_DEAL_ACCESS_DATE       TIMESTAMP WITH TIME ZONE NULL,
    MESSAGE_DESC                VARCHAR(3000)  NULL,
    RESPONSE_DESC               VARCHAR(3000)  NULL,
    COMMITMENT_LETTER_ID        INTEGER NULL,
    PARTICIPANT_CERTIFICATE_ID  INTEGER NULL,
    SIGNED_CERTIFICATE_ID       INTEGER NULL,
    DECLINED_IND                VARCHAR(1) NOT NULL DEFAULT 'N',
    DECLINED_DESC               VARCHAR(3000) NULL,
    DECLINED_DATE               TIMESTAMP WITH TIME ZONE NULL,
    REMOVED_IND                 VARCHAR(1) NOT NULL DEFAULT 'N',
    REMOVED_DATE                TIMESTAMP WITH TIME ZONE NULL,
    PRIMARY KEY ( EVENT_PARTICIPANT_ID ),
    FOREIGN KEY ( EVENT_PARTICIPANT_ID ) REFERENCES EVENT_PARTICIPANT ( EVENT_PARTICIPANT_ID ),
    FOREIGN KEY ( INVITE_RECIPIENT_ID ) REFERENCES USER_INFO ( USER_ID ),
    FOREIGN KEY ( COMMITMENT_LETTER_ID ) REFERENCES DEAL_DOCUMENT ( DEAL_DOCUMENT_ID ),
    FOREIGN KEY ( PARTICIPANT_CERTIFICATE_ID ) REFERENCES DEAL_DOCUMENT ( DEAL_DOCUMENT_ID ),
    FOREIGN KEY ( SIGNED_CERTIFICATE_ID ) REFERENCES DEAL_DOCUMENT ( DEAL_DOCUMENT_ID )
);

--------------------------------------------
--    Create Event Deal Facility Table    --
--------------------------------------------
CREATE TABLE EVENT_DEAL_FACILITY (
    EVENT_DEAL_FACILITY_ID      SERIAL  NOT NULL,
    EVENT_ID                    INTEGER NOT NULL,
    DEAL_FACILITY_ID            INTEGER NOT NULL,
    CREATED_BY_ID               INTEGER NOT NULL,
    CREATED_DATE                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY_ID               INTEGER NOT NULL,
    UPDATED_DATE                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ( EVENT_DEAL_FACILITY_ID ),
    FOREIGN KEY ( EVENT_ID ) REFERENCES EVENT_INFO ( EVENT_ID ),
    FOREIGN KEY ( DEAL_FACILITY_ID ) REFERENCES DEAL_FACILITY ( DEAL_FACILITY_ID ),
    FOREIGN KEY ( CREATED_BY_ID ) REFERENCES USER_INFO ( USER_ID ),
    FOREIGN KEY ( UPDATED_BY_ID ) REFERENCES USER_INFO ( USER_ID )
);

--------------------------------------------
-- Create Deal Participant Facility Table --
--------------------------------------------
CREATE TABLE EVENT_PARTICIPANT_FACILITY (
    EVENT_PARTICIPANT_ID        INTEGER NOT NULL,
    EVENT_DEAL_FACILITY_ID      INTEGER NOT NULL,
    INVITATION_AMT              DECIMAL(12, 2) NULL,
    COMMITMENT_AMT              DECIMAL(12, 2) NULL,
    ALLOCATION_AMT              DECIMAL(12, 2) NULL,
    CREATED_BY_ID               INTEGER NOT NULL,
    CREATED_DATE                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY_ID               INTEGER NOT NULL,
    UPDATED_DATE                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ( EVENT_PARTICIPANT_ID, EVENT_DEAL_FACILITY_ID ),
    FOREIGN KEY ( EVENT_PARTICIPANT_ID ) REFERENCES EVENT_PARTICIPANT ( EVENT_PARTICIPANT_ID ),
    FOREIGN KEY ( EVENT_DEAL_FACILITY_ID ) REFERENCES EVENT_DEAL_FACILITY ( EVENT_DEAL_FACILITY_ID ),
    FOREIGN KEY ( CREATED_BY_ID ) REFERENCES USER_INFO ( USER_ID ),
    FOREIGN KEY ( UPDATED_BY_ID ) REFERENCES USER_INFO ( USER_ID )
);

------------------------------------
--    Create Deal Batch Table     --
------------------------------------
CREATE TABLE DOCUMENT_BATCH (
    DOCUMENT_BATCH_ID           SERIAL      NOT NULL,
    DEAL_EXTERNAL_UUID          VARCHAR(36) NOT NULL,
    TRANSFER_TYPE_CD            VARCHAR(1)  NOT NULL    DEFAULT 'U',
    PROCESS_START_DATE          TIMESTAMP WITH TIME ZONE    NULL,
    PROCESS_END_DATE            TIMESTAMP WITH TIME ZONE    NULL,
    CREATED_BY_ID               INTEGER     NOT NULL,
    CREATED_DATE                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ( DOCUMENT_BATCH_ID ),
    FOREIGN KEY ( DEAL_EXTERNAL_UUID ) REFERENCES DEAL_INFO ( DEAL_EXTERNAL_UUID ),
    FOREIGN KEY ( CREATED_BY_ID ) REFERENCES USER_INFO ( USER_ID )
);

------------------------------------
-- Create Deal Batch Detail Table --
------------------------------------
CREATE TABLE DOCUMENT_BATCH_DETAIL (
    DOCUMENT_BATCH_DETAIL_ID    SERIAL       NOT NULL,
    DOCUMENT_BATCH_ID           INTEGER      NOT NULL,
    DOCUMENT_EXTERNAL_UUID      VARCHAR(55)  NOT NULL,
    DISPLAY_NAME                VARCHAR(100) NOT NULL,
    CATEGORY_NAME               VARCHAR(100) NOT NULL,
    DOCUMENT_EXT_DESC           VARCHAR(40)  NOT NULL,
    DOCUMENT_URL                VARCHAR(255) NOT NULL,
    SALESFORCE_ID               VARCHAR(30)  NULL,
    PROCESS_START_DATE          TIMESTAMP WITH TIME ZONE    NULL,
    PROCESS_END_DATE            TIMESTAMP WITH TIME ZONE    NULL,
    CREATED_BY_ID               INTEGER NOT NULL,
    CREATED_DATE                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ( DOCUMENT_BATCH_DETAIL_ID ),
    FOREIGN KEY ( DOCUMENT_BATCH_ID ) REFERENCES DOCUMENT_BATCH ( DOCUMENT_BATCH_ID ),
    FOREIGN KEY ( CREATED_BY_ID ) REFERENCES USER_INFO ( USER_ID ),
    UNIQUE ( DOCUMENT_BATCH_ID, DOCUMENT_EXTERNAL_UUID )
);

--------------------------------------------
--    Create Event Lead Facility Table    --
--------------------------------------------
CREATE TABLE EVENT_LEAD_FACILITY (
    EVENT_ID                    INTEGER NOT NULL,
    EVENT_DEAL_FACILITY_ID      INTEGER NOT NULL,
    INVITATION_AMT              DECIMAL(12, 2) NULL,
    INVITATION_DATE             TIMESTAMP WITH TIME ZONE NULL,
    COMMITMENT_AMT              DECIMAL(12, 2) NULL,
    COMMITMENT_DATE             TIMESTAMP WITH TIME ZONE NULL,
    ALLOCATION_AMT              DECIMAL(12, 2) NULL,
    ALLOCATION_DATE             TIMESTAMP WITH TIME ZONE NULL,
    CREATED_BY_ID               INTEGER NOT NULL,
    CREATED_DATE                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY_ID               INTEGER NOT NULL,
    UPDATED_DATE                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ( EVENT_ID, EVENT_DEAL_FACILITY_ID ),
    FOREIGN KEY ( EVENT_ID ) REFERENCES EVENT_INFO ( EVENT_ID ),
    FOREIGN KEY ( EVENT_DEAL_FACILITY_ID ) REFERENCES EVENT_DEAL_FACILITY ( EVENT_DEAL_FACILITY_ID ),
    FOREIGN KEY ( CREATED_BY_ID ) REFERENCES USER_INFO ( USER_ID ),
    FOREIGN KEY ( UPDATED_BY_ID ) REFERENCES USER_INFO ( USER_ID )
);

------------------------------------
--   Create Customer Data Table   --
------------------------------------
CREATE TABLE CUSTOMER_DATA (
    CUSTOMER_DATA_ID            SERIAL NOT NULL,
    MARKETPLACE_JSON            JSONB NULL,
    UNSUPPORTED_JSON            JSONB NULL,
    CREATED_BY_ID               INTEGER NOT NULL,
    CREATED_DATE                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ( CUSTOMER_DATA_ID ),
    FOREIGN KEY ( CREATED_BY_ID ) REFERENCES USER_INFO ( USER_ID )
);

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS btree_gin;

CREATE INDEX IF NOT EXISTS IDX_DEAL_EXTERNAL_ID ON CUSTOMER_DATA USING GIN ((MARKETPLACE_JSON->'deal'->>'dealExternalId'));

--------------------------------------------
-- Create Confidentiality Agreement Table --
--------------------------------------------

CREATE TABLE INSTITUTION_CONFIDENTIALITY_AGREEMENT (
    CONF_AGRMNT_ID                  SERIAL NOT NULL,
    INSTITUTION_ID                  INTEGER NOT NULL,
    CONF_AGRMNT_DESC                VARCHAR(10000)  NULL,
    CREATED_BY_ID                   INTEGER NOT NULL,
    CREATED_DATE                    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ( CONF_AGRMNT_ID ),
    FOREIGN KEY ( INSTITUTION_ID ) REFERENCES INSTITUTION_INFO ( INSTITUTION_ID ),
    FOREIGN KEY ( CREATED_BY_ID ) REFERENCES USER_INFO ( USER_ID )
);

CREATE TABLE DEAL_USER_CONF_AGRMNT_XREF (
    DEAL_ID                 INTEGER NOT NULL,
    USER_ID                 INTEGER NOT NULL,
    CONF_AGRMNT_ID          INTEGER NOT NULL,
    AGREEMENT_DATE          TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY ( DEAL_ID, USER_ID ),
    FOREIGN KEY ( DEAL_ID ) REFERENCES  DEAL_INFO ( DEAL_ID ),
    FOREIGN KEY ( USER_ID ) REFERENCES  USER_INFO ( USER_ID ),
    FOREIGN KEY ( CONF_AGRMNT_ID ) REFERENCES INSTITUTION_CONFIDENTIALITY_AGREEMENT (CONF_AGRMNT_ID)
);

CREATE TABLE FEATURE_FLAG_INFO (
    FEATURE_FLAG_ID             SERIAL       NOT NULL,
    FEATURE_NAME                VARCHAR(80)  NOT NULL,
    DESCRIPTION                 VARCHAR(100) NOT NULL,
    IS_ENABLED                  VARCHAR(1)   NOT NULL DEFAULT 'N',
    CREATED_BY_ID               INTEGER      NOT NULL,
    CREATED_DATE                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY_ID               INTEGER      NOT NULL,
    UPDATED_DATE                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ( FEATURE_FLAG_ID ),
    UNIQUE ( FEATURE_NAME ),
    FOREIGN KEY ( CREATED_BY_ID ) REFERENCES USER_INFO ( USER_ID ),
    FOREIGN KEY ( UPDATED_BY_ID ) REFERENCES USER_INFO ( USER_ID )
);

CREATE TABLE EMAIL_NOTIFICATION_INFO (
    EMAIL_NOTIFICATION_ID       SERIAL      NOT NULL,
    DEAL_ID                     INTEGER     NOT NULL,
    TEMPLATE_JSON               JSONB       NULL,
    EMAIL_TYPE_CD               VARCHAR(5)  NOT NULL,
    PROCESSED_IND               VARCHAR(1)  NOT NULL DEFAULT 'N',
    CREATED_DATE                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ( EMAIL_NOTIFICATION_ID ),
    FOREIGN KEY ( DEAL_ID ) REFERENCES DEAL_INFO ( DEAL_ID )
);