name: Unit Tests

on:
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]

jobs:
  gradle-test:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
    
      - name: Run gradle test
        run: gradle clean test

      - name: Store reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          retention-days: 3
          path: |
            **/build/reports/
            **/build/test-results/
